<img src="https://github.com/Ch3ddarr/DSB-Unit-02/blob/main/assets/ga-logo.png?raw=1" style="float: left; margin: 20px; height: 55px">

# Introduction to `pandas`

---

### About
`pandas` is the most popular python package for managing datasets and is used extensively by data scientists.

### Learning Objectives
- Explore the characteristics of a dataset at a high level with `pandas`.

### Notebook Guide
An exercise in practising:

- Reading data with `pandas`
- Exploring and manipulating data with `pandas`
    - Column operations
    - Filtering
    - Sorting
    - Writing data

# Scenario

You're an analyst working for CoolBricks - a new toy company who wants to compete with LEGO by producing their own bricks and sets. To better understand what kind of sets to create and at what price points, you are tasked with analyzing LEGO's catalogue over time.

The data comes from Kaggle: [https://www.kaggle.com/datasets/alexracape/lego-sets-and-prices-over-time](https://www.kaggle.com/datasets/alexracape/lego-sets-and-prices-over-time)

We are going to use `pandas` to read and explore this data.

### Business question

What is the biggest set we could build (in terms of number of pieces) and what sort of price would we want to charge?

#### 1. Import `pandas` and read in the LEGO dataset

In [1]:
import pandas as pd

#### 2. So we can focus on just the columns that help answer the question, select only the following columns into a new `DataFrame` variable:

- name
- theme
- number of pieces
- retail price (USD_MSRP)

In [17]:
lego = pd.read_csv('https://raw.githubusercontent.com/Ch3ddarr/DSB-Unit-02/refs/heads/main/data/lego.csv')
lego_copy = lego[['Name', 'Theme', 'Pieces', 'USD_MSRP']].copy()

#### 3. How many sets have a price greater than $100?

In [18]:
lego_copy[lego_copy['USD_MSRP']>100].count()

Name        380
Theme       380
Pieces      374
USD_MSRP    380
dtype: int64

#### 4. What are the top 10 sets with the highest number of pieces?

In [19]:
lego_copy[lego_copy['USD_MSRP']>100].sort_values(by='USD_MSRP', ascending=False).head(10)

,Name,Theme,Pieces,USD_MSRP
11928,Millennium Falcon,Star Wars,7541.0,849.99
12854,Imperial Star Destroyer,Star Wars,4784.0,699.99
13449,Titanic,Icons,9090.0,679.99
13946,Eiffel Tower,Icons,10001.0,629.99
14380,The Razor Crest,Star Wars,6187.0,599.99
14408,Hulkbuster,Marvel Super Heroes,4049.0,549.99
12942,Colosseum,Icons,9036.0,549.99
14433,Hogwarts Express - Collectors' Edition,Harry Potter,5129.0,499.99
6783,Ultimate Collector's Millennium Falcon,Star Wars,5197.0,499.99
13691,Cat D11 Bulldozer,Technic,3854.0,499.99

#### 5. Create a new column to measure "price per piece", which should be the price (USD_MSRP) divided by the number of pieces

In [20]:
lego_copy['PPP'] = lego_copy['USD_MSRP'] / lego_copy['Pieces']

#### 6. Use this column to find the top 10 most expensive sets by "price per piece"

In [23]:
lego_copy.sort_values(by='PPP', ascending=False).head(10)

,Name,Theme,Pieces,USD_MSRP,PPP
13892,Character Pack Series 3 - Complete,Super Mario,0.0,4.99,inf
13806,LEGO Minifigures - Marvel Studios Series {Box ...,Collectable Minifigures,0.0,29.94,inf
14251,LEGO Minifigures - Series 22 {Box of 6 random ...,Collectable Minifigures,0.0,29.94,inf
9653,EV3 Intelligent Brick,Mindstorms,1.0,224.95,224.950
6342,NXT Intelligent Brick,Mindstorms,1.0,169.99,169.990
7695,Intelligent NXT Brick (Black),Mindstorms,1.0,169.99,169.990
13755,Small Hub,Education,2.0,214.95,107.475
9654,DC Rechargeable Battery,Education,1.0,99.95,99.950
8197,NXT DC Rechargeable Battery,Education,1.0,79.99,79.990
12927,Boost Hub,Powered Up,1.0,79.99,79.990

#### 7. Narrow the search to show the top 10 most expensive sets by "price per piece" for the "Icons" theme *only*

In [27]:
lego_copy.sort_values(by='PPP', ascending=False)[lego_copy['Theme']=='Icons'].head(10)

/tmp/ipykernel_1668/3594961348.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  lego_copy.sort_values(by='PPP', ascending=False)[lego_copy['Theme']=='Icons'].head(10)

                                  Name  Theme  Pieces  USD_MSRP       PPP
13941                    Optimus Prime  Icons  1508.0    179.99  0.119357
13943       Chevrolet Camaro Z/28 1969  Icons  1456.0    169.99  0.116751
13450                      Porsche 911  Icons  1458.0    169.99  0.116591
13440       Adidas Originals Superstar  Icons   731.0     79.99  0.109425
13939  Back to the Future Time Machine  Icons  1872.0    199.99  0.106832
13942                     Loop Coaster  Icons  3756.0    399.99  0.106494
14441   Land Rover Classic Defender 90  Icons  2336.0    239.99  0.102735
13446       Queer Eye – The Fab 5 Loft  Icons   974.0     99.99  0.102659
12940              Ghostbusters ECTO-1  Icons  2352.0    239.99  0.102037
13617              Everyone is Awesome  Icons   346.0     34.99  0.101127

#### 8. What are the top 10 cheapest sets by "price per piece" in the "Icons" theme?

In [28]:
lego_copy.sort_values(by='PPP', ascending=False)[lego_copy['Theme']=='Icons'].tail(10)

/tmp/ipykernel_1668/688921078.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  lego_copy.sort_values(by='PPP', ascending=False)[lego_copy['Theme']=='Icons'].tail(10)

                                  Name  Theme  Pieces  USD_MSRP  PPP
13598  Mini Adidas Originals Superstar  Icons    92.0       NaN  NaN
13940                              {?}  Icons     NaN       NaN  NaN
13949                              {?}  Icons     NaN       NaN  NaN
14086                     Vintage Taxi  Icons   163.0       NaN  NaN
14117                   Forest Hideout  Icons   258.0       NaN  NaN
14127               Eiffel's Apartment  Icons   228.0       NaN  NaN
14439                              {?}  Icons     NaN       NaN  NaN
14539                Blacktron Cruiser  Icons   356.0       NaN  NaN
14540          BIONICLE Tahu and Takua  Icons   219.0       NaN  NaN
14545                     Moving Truck  Icons   301.0       NaN  NaN

#### 9. Export the `DataFrame` you created in question 2. to a new CSV file.

### Reflection

What is your answer to the business question? Here it is as a reminder:

> What is the biggest set we could build (in terms of number of pieces) and what sort of price would we want to charge?

Reflect on your experience. How was working with `pandas` compared to other tools you already know?